// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface SiteConfig {
  /**
   * Attach and send username and ip-address (Not GDPR friendly)
   */
  sendPersonalInformation: boolean;
}
